pull_request_rules:
  - name: Automatic merge
    conditions:
      - base=master
      - label="dependencies"
      - author=dependabot[bot]
    actions:
      merge:
        method: merge
        strict: true
