
title:               "mbtamuli's scratchpad"
tagline:             'To infinity and beyond'
description:         'Linux enthusiast. Tinkerer. Love me a challenge.'
url:                 https://mbtamuli.github.io/
baseurl:             ''
paginate:            5
future:              true

# About/contact
author:
  name:              Mriyam Bikash Tamuli
  url:               https://twitter.com/mbtamuli
  email:             mbtamuli@gmail.com

# Custom vars
version:             0.0.1

# Google Analytics
analytics:
  provider               : google
  google:
    tracking_id          : 'UA-123129368-1'

plugins:
  - jekyll-paginate
  - jemoji
